# Generated by Django 5.1.6 on 2025-02-10 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modificado em")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Descrição")),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="Data de vencimento")),
                ("delivery_date", models.DateTimeField(blank=True, null=True, verbose_name="Data de entrega")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        choices=[(1, "Baixa"), (2, "Média"), (3, "Alta"), (4, "Crítica")],
                        default=1,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "A fazer"), (2, "Fazendo"), (3, "Feito"), (4, "Cancelado")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["status", "priority", "due_date", "title"],
            },
        ),
    ]
